#General Commands
tapply(WHO$ChildMortality,WHO$Region,min)
tapply(WHO$LiteracyRate,WHO$Region,min,na.rm=TRUE)
boxplot(WHO$LifeExpectancy~WHO$Region,xlab="",ylab= "Lifeexpectanxy",main= "lifeexpectancyofcountriesbyregion")
table(WHO$Region)

getwd()
USDA=read.csv('USDA.CSV')
str(USDA)
summary(USDA)
USDA$Sodium
which.max(USDA$Sodium)
names(USDA)
USDA$Description[which.max(USDA$Sodium)]
HighSodium  = subset(USDA,Sodium>10000)
nrow(HighSodium)
HighSodium$Description
match("CAVIAR",USDA$Description)
USDA$Sodium[match("CAVIAR",USDA$Description)]
summary(USDA$Sodium)
sd(USDA$Sodium,na.rm=TRUE)
plot(USDA$Protein,USDA$TotalFat)
plot(USDA$Protein,USDA$TotalFat, xlab="Protein",ylab="Fat",main="Protein vsFat")
hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of VitC")
hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of VitC", xlim=c(0,100),breaks = 2000)
boxplot(USDA$Sugar,ylab = "Sugar Levels", main = "Boxplot of Sugar levels")
USDA$Sodium[1] > mean(USDA$Sodium,na.rm = TRUE)
HighSodium = USDA$Sodium > mean(USDA$Sodium,na.rm = TRUE)
str(HighSodium)
USDA$HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium,na.rm = TRUE))
str(HighSodium)
str(USDA)
USDA$HighCarbs = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate,na.rm = TRUE))
str(USDA)
table(USDA$HighSodium)
table(USDA$HighSodium,USDA$HighCarbs)
tapply( USDA$Iron,USDA$HighCarbs, mean, na.rm=TRUE)
tapply( USDA$VitaminC,USDA$HighCarbs, max, na.rm=TRUE)
tapply( USDA$VitaminC,USDA$HighCarbs, summary, na.rm=TRUE)
table(mvt$Month,mvt$ID)
table(mvt$Month)
table(mvt$Weekday)
table(mvt$Month,mvt$Arrest)
hist(mvt$Date, breaks=100)
boxplot(mvt$Date,col=mvt$Arrest)

Top5 = subset(mvt,LocationDescription=="STREET"|LocationDescription=="ALLEY"|LocationDescription=="PARKING LOT/GARAGE(NON.RESID.)"|LocationDescription=="GAS STATION"|LocationDescription=="DRIVEWAY - RESIDENTIAL")
Top5$LocationDescription = factor(Top5$LocationDescription)
str(Top5)
table(Top5$Weekday,Top5$LocationDescription)

