download.file(url="https://d37djvu3ytnwxt.cloudfront.net/asset-v1:MITx+15.071x_3+1T2016+type@asset+block/AnonymityPoll.csv", destfile = "AnonymityPoll.csv", method = 'curl')
AP= read.csv('AnonymityPoll.csv')
count(subset(AP,Smartphone=1))
table(AP$Smartphone)
table(AP$State,AP$Region)
table(AP$Smartphone,AP$Internet.Use)
table(is.na(AP$Internet.Use))
limited = subset(AP,AP$Smartphone ==1 | AP$Internet.Use ==1)
str(limited)
summary(limited)
tapply(AP$Tried.Masking.Identity,AP,mean)
max(table(limited$Age, limited$Info.On.Internet))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet)).
jitter(c(1,2,3))
tapply(AP$Info.On.Internet,AP$Smartphone,mean,na.rm=TRUE)
tapply(AP$Tried.Masking.Identity,AP$Smartphone,mean,na.rm=TRUE)
